优化action相关配置，action统一规范命名
Co-authored-by: liuyi<larry.liuyi@huawei.com>



# message auto-generated for no-merge-commit merge:
!144 merge master into master

优化action相关配置，action统一规范命名

Created-by: Larry_liuyi
Commit-by: liuyi
Merged-by: cann-robot
Description: ## 描述
优化action相关配置，action统一规范命名

## 关联的Issue
<!-- 如果这个PR是为了解决特定的Issue，请在这里提供Issue链接。例如：关联Issue #123-->
<!-- 如果这个PR是为了解决特定的问题单，请在这里描述问题单单号。-->

## 测试
<!--描述进行了哪些测试来验证你的改动。包括但不限于二级冒烟、算子泛化等。-->

## 文档更新
<!--如果这个PR包含文档的更新，请在这里指出。例如：更新了README.md文件。-->

## 类型标签
<!--  [x] 表示选中 -->
- [ ] Bug修复
- [ ] 新特性
- [ ] 性能优化
- [ ] 文档更新
- [x ] 其他，请描述：优化action相关配置，action统一规范命名




See merge request: cann/pyasc!144

diff --git a/.gitcode/workflows/PR-pipeline_pyasc.yml b/.gitcode/workflows/PR-pipeline_pyasc.yml
--- a/.gitcode/workflows/PR-pipeline_pyasc.yml
+++ b/.gitcode/workflows/PR-pipeline_pyasc.yml
@@ -1,4 +1,4 @@
-name: pyasc_action
+name: PR-pipeline_pyasc
 
 concurrency:
   max: 5
@@ -48,7 +48,9 @@ stages:
               echo "Compile_Ascend_X86: ${{ steps.revise_image.outputs.Compile_Ascend_X86 }}"
               echo ${org_name}
         if: "${{ default() }}"
-        runs-on: ["codearts-hosted", "ubuntu-latest", "x64", "large"]
+        runs-on: ["dedicate-hosted", "x64", "small"]
+        container:
+          image: swr.cn-north-4.myhuaweicloud.com/ci_cann/ubuntu20.04.05_x86:k8s_v1.1006
       JOB_pr:
         name: Test_get-pr
         steps:
@@ -57,8 +59,17 @@ stages:
             identifier: process_checkout
             uses: checkout
             with:
-              ref: ${{ atomgit.event.pull_request.merge_commit_sha || atomgit.sha }}
+              ref: ${{ atomgit.event.pull_request.merge_commit_sha }}
               token: ${{ secrets.GIT_TOKEN }}
+          - name: Check merge commit sha
+            shell: bash
+            run: |
+              # === shell 核心逻辑 ===
+              if [[ -z "${{ atomgit.event.pull_request.merge_commit_sha }}" ]]; then
+                echo "virtual merging failed, message: Conflict detected"
+                exit 1
+              fi
+              echo "${{ atomgit.event.pull_request.merge_commit_sha }}"
           -
             name: get_pr
             identifier: get_pr
@@ -218,6 +229,7 @@ stages:
             identifier: process_checkout
             uses: checkout
             with:
+              ref: ${{ atomgit.event.pull_request.merge_commit_sha }}
               token: ${{secrets.GIT_TOKEN}}
               path: "./runner"
           -
